version: "3"

services:
 nginx:
  build: ./nginx
  image: nginx:test
  container_name: test-nginx
  ports:
   - 80:80
  volumes:
   - /home/ylee/data/html:/var/www/html
  restart: always
  tty: true
  stdin_open: true
 wordpress:
  build: ./wordpress
  image: wp:test
  container_name: test-wp
  expose:
   - "9000"
  volumes:
   - /home/ylee/data/html:/wordpress
  restart: always
  tty: true
  stdin_open: true
 mariadb:
  build: ./mariadb
  image: db:test
  container_name: test-db
  expose:
   - "3306"
  volumes:
   - /home/ylee/data/mariadb:/var/lib/mysql
  restart: always
  tty: true
  stdin_open: true

